---
# 将本地代码同步解压至远端

- name: copy pkgs
  copy: src={{ local_path }}/{{ prj_name }}/{{ deploy_name }}.tgz dest={{ pkgs_dir }}/ owner={{ruser}} group={{ruser}}

- name: extract pkgs
  command: /bin/tar zxf  {{ pkgs_dir }}/{{ deploy_name }}.tgz chdir={{ pkgs_dir }}
